package ssafy.E207.global.common.enums;

public enum StompMessageType {
	REQUEST_READY_CHANGE,
	REQUEST_BATTLE_START,
	REQUEST_TURN_SWAP,
	REQUEST_LAUGHED,
	REQUEST_SURRENDER,
	REQUEST_REPORT,

	RESPONSE_MATCHMAKING_SUCCESS,
	RESPONSE_READY_CHANGE,
	RESPONSE_BATTLE_START,
	RESPONSE_TURN_SWAP,
	RESPONSE_ROUND_END,
	RESPONSE_BATTLE_END,
	RESPONSE_ERROR,
	RESPONSE_PARTICIPANT_JOINED,
	RESPONSE_HOST_CHANGED,
	CHAT,
	RESPONSE_ROOM_DESTROYED,
	RESPONSE_PARTICIPANT_LEFT,
	RESPONSE_REPORTED
}